[workspace]
members = [
  "server",
  "types",
  "client",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.*", default-features = false }
ndarray = { version = "0.15.6", features = ["serde"] }
itertools = "0.10.0"
clap = { version = "4.5.4", features = ["derive"] }
