[workspace]
members = [
  "server",
  "types",
  "client",
  "tracer",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.*", features = ["derive"] }
bincode = "1.3.3"
ndarray = { version = "0.15.6", features = ["serde"] }
itertools = "0.10.0"
clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
once_cell = "1.19.0"
pretty_assertions = "1.4.0"
tracing = "0.1"
